apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-api
  template:
    metadata:
      labels:
        app: credit-api
    spec:
      containers:
      - name: credit-api
        image: credit-scoring-api:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000